[MNIST]
path = "vision/mnist"
notebook = "mlp.jl"
deps = ["vae.jl"]

[char-rnn]
path = "text/char-rnn"
notebook = "char-rnn.jl"

[conv]
path = "vision/mnist/conv/"
notebook = "conv.jl"
deps = ["mnistsample.png"]